# Generated by Django 2.2.5 on 2019-11-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reaccount.Group')),
                ('name', models.TextField(blank=True)),
                ('ID', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('school', models.TextField(blank=True)),
                ('identification', models.TextField(blank=True)),
                ('access', models.TextField(blank=True)),
            ],
            bases=('reaccount.group',),
        ),
    ]
