# Generated by Django 2.2.7 on 2019-11-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='Summary_Question_ID',
        ),
        migrations.RemoveField(
            model_name='summit',
            name='Summit_Question_ID',
        ),
        migrations.AddField(
            model_name='summary',
            name='Summary_Question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DataBase.Question'),
        ),
        migrations.AddField(
            model_name='summit',
            name='Summit_Question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DataBase.Question'),
        ),
    ]
