# Generated by Django 2.2.7 on 2019-12-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_auto_20191129_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Group_Question',
            field=models.ManyToManyField(blank=True, to='DataBase.Question'),
        ),
        migrations.AddField(
            model_name='group',
            name='Group_User',
            field=models.ManyToManyField(blank=True, to='DataBase.User'),
        ),
    ]
