# Generated by Django 2.2.7 on 2019-12-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_auto_20191203_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=40)),
                ('Category_Description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='Question_Category',
            field=models.ManyToManyField(blank=True, related_name='Category', to='DataBase.Category'),
        ),
    ]
