# Generated by Django 2.2.7 on 2019-12-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0009_auto_20191212_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='Summary_Runtime',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summit',
            name='Summit_Runtime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
