# Generated by Django 2.2.7 on 2019-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_auto_20191212_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='Rank_Attend',
            field=models.BooleanField(default=False),
        ),
    ]
