# Generated by Django 2.2.7 on 2019-12-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_auto_20191225_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Summary_Runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summit',
            name='Summit_Runtime',
            field=models.IntegerField(default=0),
        ),
    ]
