# Generated by Django 2.2.7 on 2020-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0012_auto_20191226_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='Summary_Language',
            field=models.CharField(default='C', max_length=10),
        ),
        migrations.AddField(
            model_name='summit',
            name='Summit_Language',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
