# Generated by Django 2.2.7 on 2019-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_auto_20191202_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Group_Question',
            field=models.ManyToManyField(blank=True, related_name='Group', to='DataBase.Question'),
        ),
        migrations.AlterField(
            model_name='group',
            name='Group_User',
            field=models.ManyToManyField(blank=True, related_name='Group', to='DataBase.User'),
        ),
    ]
