# Generated by Django 2.2.7 on 2019-12-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_auto_20191202_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Question_Html_Filename',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_Js_Filename',
        ),
        migrations.AlterField(
            model_name='question',
            name='Question_ID',
            field=models.CharField(max_length=40),
        ),
    ]
