# Generated by Django 2.2.7 on 2019-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_auto_20191203_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='Summary_Count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
