# Generated by Django 2.2.7 on 2019-12-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0010_auto_20191216_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Chat_Date_Str',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='chat',
            name='Chat_Time_Str',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
