# Generated by Django 2.2.7 on 2019-11-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_Name', models.CharField(max_length=40)),
                ('Group_Chat_Maximum', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(max_length=40)),
                ('Question_ID', models.PositiveIntegerField(default=0)),
                ('Question_Current_Count', models.PositiveIntegerField(default=1)),
                ('Question_difficulty', models.CharField(default='normal', max_length=10)),
                ('Question_AC_Count', models.PositiveIntegerField(default=0)),
                ('Question_Summit_Time', models.PositiveIntegerField(default=0)),
                ('Question_Create_Time', models.DateTimeField(auto_now_add=True)),
                ('Question_Html_Filename', models.CharField(blank=True, max_length=100)),
                ('Question_Js_Filename', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_ID', models.PositiveIntegerField(default=0)),
                ('User_Email', models.EmailField(default='', max_length=254)),
                ('User_Password', models.CharField(max_length=40)),
                ('User_School', models.CharField(blank=True, max_length=40)),
                ('User_Identification', models.CharField(default='student', max_length=8)),
                ('User_Access', models.CharField(default='0000000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summit_Question_ID', models.PositiveIntegerField(default=0)),
                ('Summit_Time', models.DateTimeField(auto_now_add=True)),
                ('Summit_Output', models.CharField(default='WA', max_length=10)),
                ('Summit_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Summit', to='DataBase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_Question_ID', models.PositiveIntegerField(default=0)),
                ('Summary_Count', models.PositiveIntegerField(default=0)),
                ('Summary_AC_Count', models.PositiveIntegerField(default=0)),
                ('Summary_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Summary', to='DataBase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank_Order', models.PositiveIntegerField(default=0)),
                ('Rank_Question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rank', to='DataBase.Question')),
                ('Rank_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rank', to='DataBase.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_Message', models.CharField(blank=True, max_length=255)),
                ('Chat_Time', models.DateTimeField(auto_now_add=True)),
                ('Chat_Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chat', to='DataBase.Group')),
                ('Chat_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='DataBase.User')),
            ],
        ),
    ]
