# Generated by Django 2.2.5 on 2019-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='groupname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
