# Generated by Django 2.2.5 on 2019-11-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(max_length=40)),
                ('Question_difficulty', models.CharField(default='normal', max_length=10)),
                ('Question_AC_Count', models.PositiveIntegerField(default=0)),
                ('Question_Summit_Time', models.PositiveIntegerField(default=0)),
                ('Question_Create_Time', models.DateTimeField(auto_now_add=True)),
                ('Question_Html_Filename', models.CharField(blank=True, max_length=100)),
                ('Question_Js_Filename', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=40)),
                ('User_ID', models.PositiveIntegerField()),
                ('User_Email', models.EmailField(default='', max_length=254)),
                ('User_Password', models.CharField(max_length=40)),
                ('User_School', models.CharField(blank=True, max_length=40)),
                ('User_Identification', models.CharField(default='student', max_length=8)),
                ('User_Access', models.CharField(default='0000000000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summit_Question', models.CharField(max_length=40)),
                ('Summit_Time', models.DateTimeField(auto_now_add=True)),
                ('Summit_Output', models.CharField(default='WA', max_length=10)),
                ('Summit_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summit', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary_Question', models.CharField(max_length=40)),
                ('Summary_Count', models.PositiveIntegerField(default=0)),
                ('Summary_AC_Count', models.PositiveIntegerField(default=0)),
                ('Summary_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summary', to='login.User')),
            ],
        ),
    ]
